// wp-proekt/Web/wpproekt/src/app/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../services/api.service';
import { Product } from '../models/Product';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css']
})
export class ProductDetailsComponent implements OnInit {

  constructor(private service: ApiService, private route: ActivatedRoute) { }

  productId: number
  product: Product

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.productId = +params['id']
      this.service.getProduct(this.productId).subscribe(data => {
        this.product = data
        console.log(data)
      })
    })
  }

  deleteProduct(){
    this.service.deleteProduct(this.product.id)
  }

}

<div *ngIf = "product">
    <h1>{{product.name}}</h1>
    <div>{{product.description}}</div>
    <p style="color:limegreen">{{product.price}}</p>
    <img [src]="product.imageUrl">
    <a [routerLink]="['/products', product.id, 'edit']">Edit</a>
    <button (click)="deleteProduct()">Delete</button>
</div>

<a routerLink="/products">Back to products</a>

// Web/xor-designs/src/components/products/ProductDetails.vue
<template>
    <div>
        <router-link v-if="product" :to="{ name: 'ProductEdit', params: { id: product.ID }}" class="button is-success">Edit</router-link>
        <b-button type="is-danger" @click="deleteProduct()">Delete</b-button>
        <h1>{{product.Name}}</h1>
        <img :src="product.ImageUrl">
        <hr>
        <p>{{product.Description}}</p>
        <p class="has-text-success">${{product.Price}}</p>
        <hr>
        <router-link :to="{ name: 'Products' }">Back to Products</router-link>
    </div>
</template>

<script>
import axios from 'axios'
export default {
    name: 'ProductDetails',
    data: () => {
        return {
            product: {}
        }
    },
    created: function () {
        let id = this.$route.params.id
        fetch(`http://localhost:60402/api/Products/${id}`)
        .then(response => response.json())
        .then(data => this.product = data)
    },
    methods: {
        deleteProduct () {
            let axiosConfig = {
                method: 'DELETE',
                url: `http://localhost:60402/api/Products/${this.product.ID}`
            }

            axios(axiosConfig).then(response => {
                console.log(response)
                this.$router.push({ name: 'Products' })
            })
        }
    }
}
</script>

<style scoped>
</style>
