// Web/xor-designs/src/components/posts/PostAddEdit.vue
<template>
  <div>
    <button class="button is-dark" v-if="bEditEnabled">EDIT MODE</button>

    <b-field label="Title">
      <b-input v-model="post.Title"></b-input>
    </b-field>

     <b-field label="Content">
      <b-input v-model="post.Content"></b-input>
    </b-field>

     <b-field label="Author Name">
      <b-input v-model="post.AuthorName"></b-input>
    </b-field>

    <div class="field">
      <b-switch v-model="bPreviewEnabled"
      type="is-info">
          Preview: {{bPreviewEnabled ? 'ON' : 'OFF'}}
      </b-switch>
    </div>

    <div v-if="bPreviewEnabled">
      <div v-html="post.Content"></div>
    </div>

    <b-button type="is-info" @click="submit()">Submit</b-button>
  </div>
</template>

<script>
import PostsService from '../../services/PostsService'
export default {
    name: 'PostAddEdit',
    props: ['bEditEnabled'],
    data: () => {
        return {
            post: {},
            bPreviewEnabled: true
        }
    },
    created: function () {
      if (this.bEditEnabled) {
        let id = this.$route.params.id
        fetch(`http://localhost:60402/api/Posts/${id}`)
        .then(response => response.json())
        .then(data => this.post = data)
      }
    },
    methods: {
      submit() {
        if(this.bEditEnabled){
          PostsService.putPost(this.post)
        } else {
          PostsService.postPost(this.post)
        }
      }
    }
}
</script>

<style scoped>
</style>

// wp-proekt/Web/wpproekt/src/app/post-add-edit/post-add-edit.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ApiService } from '../services/api.service';
import { Post } from '../models/Post';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-post-add-edit',
  templateUrl: './post-add-edit.component.html',
  styleUrls: ['./post-add-edit.component.css']
})
export class PostAddEditComponent implements OnInit {

  constructor(private service: ApiService, private route: ActivatedRoute) { }

  postId: number;
  post: Post;
  bEditEnabled: boolean = false;

  @Input()
  postTitle: string;
  @Input()
  postContent: string;
  @Input()
  isDraft: boolean;
  @Input()
  bPreviewEnabled: boolean = false;

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.postId = params['id']
      if(this.postId){

        this.bEditEnabled = true

        this.service.getPost(this.postId).subscribe(data => {
          this.post = data
          this.postTitle = this.post.title
          this.postContent = this.post.content
          this.isDraft = this.post.isDraft
        })
      }
    })
  }

  submitPost(){
    if(this.bEditEnabled){
      console.log("Sending PUT request...")
      this.service.putPost({
        id: this.post.id,
        title: this.postTitle,
        content: this.postContent,
        authorName: this.post.authorName,
        isDraft: false
      })
    } else {
      console.log("Sending POST request...")
      this.service.postPost({
        title: this.postTitle,
        authorName: "Admin",
        content: this.postContent,
        isDraft: false
      })
    }
  }

}

<div>
    <label for="title">Title:</label>
    <input type="text" name="title" placeholder="Title" [(ngModel)] = "postTitle">
    <p>{{postTitle}}</p>
    <label for="content">Content:</label>
    <textarea rows="8" cols="50" name="content" placeholder="Content" [(ngModel)] = "postContent"></textarea>
    <p>{{postContent}}</p>
    <label for="preview">Preview HTML?</label>
    <input type="checkbox" name="preview" [(ngModel)] = "bPreviewEnabled">
    <div *ngIf="bPreviewEnabled" [innerHtml] = "postContent | noSanitize"></div>
    <button (click) = "submitPost()">Submit</button>
</div>
